### ISSUE TITLE
gpu-opt fails with GNU fortran compiler

### ISSUE THREAD

**Issue by johnmauff** [george-bryan/CM1#87]
The gpu-opt branch of the code fails to execute using the GNU fortran compiler using the namelist.figureA.cpu namelist.  

The traceback is as follows:

 nstat,stat_out =           93          89
 cm1out_stats.ctl                                                                                                        

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2b3cbebe0bff in ???
#1  0x2b3cbf703b55 in ???
#2  0x2b3cbf704752 in ???
#3  0x2b3cbe267f22 in close_unit_1
	at ../../../libgfortran/io/unit.c:745
#4  0x6938d0 in ???
#5  0x8bd7e0 in ???
#6  0x402e5c in ???
#7  0x2b3cbf6aaa34 in ???
#8  0x402e98 in ???
	at ../sysdeps/x86_64/start.S:118
#9  0xffffffffffffffff in ???
MPT ERROR: MPI_COMM_WORLD rank 0 has terminated without calling MPI_Finalize()
	aborting job

**Comment by johnmauff** [comment]
A work around for this issue is to comment out the call to statpack.
